export const PLACE_CATEGORY_DEFINITIONS = [
  { id: 'korean', label: '한식', iconKey: 'bowl' },
  { id: 'chinese', label: '중식', iconKey: 'cookingPot' },
  { id: 'japanese', label: '일식', iconKey: 'fish' },
  { id: 'western', label: '양식', iconKey: 'pizza' },
  { id: 'asian', label: '아시아 음식', iconKey: 'wheat' },
  { id: 'global', label: '세계 음식', iconKey: 'globe' },
  { id: 'quick', label: '간편식', iconKey: 'sandwich' },
  { id: 'cafe', label: '카페·디저트', iconKey: 'coffee' },
  { id: 'bar', label: '주점', iconKey: 'beer' },
  { id: 'other', label: '기타', iconKey: 'utensils' },
]

// Google Places Table A의 Food and Drink 목록 스냅샷.
// 기준: 2026-07-20. 외부 값은 닫힌 enum으로 취급하지 않고 새 값은 other로 보낸다.
export const GOOGLE_FOOD_PRIMARY_TYPES = [
  'acai_shop',
  'afghani_restaurant',
  'african_restaurant',
  'american_restaurant',
  'argentinian_restaurant',
  'asian_fusion_restaurant',
  'asian_restaurant',
  'australian_restaurant',
  'austrian_restaurant',
  'bagel_shop',
  'bakery',
  'bangladeshi_restaurant',
  'bar',
  'bar_and_grill',
  'barbecue_restaurant',
  'basque_restaurant',
  'bavarian_restaurant',
  'beer_garden',
  'belgian_restaurant',
  'bistro',
  'brazilian_restaurant',
  'breakfast_restaurant',
  'brewery',
  'brewpub',
  'british_restaurant',
  'brunch_restaurant',
  'buffet_restaurant',
  'burmese_restaurant',
  'burrito_restaurant',
  'cafe',
  'cafeteria',
  'cajun_restaurant',
  'cake_shop',
  'californian_restaurant',
  'cambodian_restaurant',
  'candy_store',
  'cantonese_restaurant',
  'caribbean_restaurant',
  'cat_cafe',
  'chicken_restaurant',
  'chicken_wings_restaurant',
  'chilean_restaurant',
  'chinese_noodle_restaurant',
  'chinese_restaurant',
  'chocolate_factory',
  'chocolate_shop',
  'cocktail_bar',
  'coffee_roastery',
  'coffee_shop',
  'coffee_stand',
  'colombian_restaurant',
  'confectionery',
  'croatian_restaurant',
  'cuban_restaurant',
  'czech_restaurant',
  'danish_restaurant',
  'deli',
  'dessert_restaurant',
  'dessert_shop',
  'dim_sum_restaurant',
  'diner',
  'dog_cafe',
  'donut_shop',
  'dumpling_restaurant',
  'dutch_restaurant',
  'eastern_european_restaurant',
  'ethiopian_restaurant',
  'european_restaurant',
  'falafel_restaurant',
  'family_restaurant',
  'fast_food_restaurant',
  'filipino_restaurant',
  'fine_dining_restaurant',
  'fish_and_chips_restaurant',
  'fondue_restaurant',
  'food_court',
  'french_restaurant',
  'fusion_restaurant',
  'gastropub',
  'german_restaurant',
  'greek_restaurant',
  'gyro_restaurant',
  'halal_restaurant',
  'hamburger_restaurant',
  'hawaiian_restaurant',
  'hookah_bar',
  'hot_dog_restaurant',
  'hot_dog_stand',
  'hot_pot_restaurant',
  'hungarian_restaurant',
  'ice_cream_shop',
  'indian_restaurant',
  'indonesian_restaurant',
  'irish_pub',
  'irish_restaurant',
  'israeli_restaurant',
  'italian_restaurant',
  'japanese_curry_restaurant',
  'japanese_izakaya_restaurant',
  'japanese_restaurant',
  'juice_shop',
  'kebab_shop',
  'korean_barbecue_restaurant',
  'korean_restaurant',
  'latin_american_restaurant',
  'lebanese_restaurant',
  'lounge_bar',
  'malaysian_restaurant',
  'meal_delivery',
  'meal_takeaway',
  'mediterranean_restaurant',
  'mexican_restaurant',
  'middle_eastern_restaurant',
  'mongolian_barbecue_restaurant',
  'moroccan_restaurant',
  'noodle_shop',
  'north_indian_restaurant',
  'oyster_bar_restaurant',
  'pakistani_restaurant',
  'pastry_shop',
  'persian_restaurant',
  'peruvian_restaurant',
  'pizza_delivery',
  'pizza_restaurant',
  'polish_restaurant',
  'portuguese_restaurant',
  'pub',
  'ramen_restaurant',
  'restaurant',
  'romanian_restaurant',
  'russian_restaurant',
  'salad_shop',
  'sandwich_shop',
  'scandinavian_restaurant',
  'seafood_restaurant',
  'shawarma_restaurant',
  'snack_bar',
  'soul_food_restaurant',
  'soup_restaurant',
  'south_american_restaurant',
  'south_indian_restaurant',
  'southwestern_us_restaurant',
  'spanish_restaurant',
  'sports_bar',
  'sri_lankan_restaurant',
  'steak_house',
  'sushi_restaurant',
  'swiss_restaurant',
  'taco_restaurant',
  'taiwanese_restaurant',
  'tapas_restaurant',
  'tea_house',
  'tex_mex_restaurant',
  'thai_restaurant',
  'tibetan_restaurant',
  'tonkatsu_restaurant',
  'turkish_restaurant',
  'ukrainian_restaurant',
  'vegan_restaurant',
  'vegetarian_restaurant',
  'vietnamese_restaurant',
  'western_restaurant',
  'wine_bar',
  'winery',
  'yakiniku_restaurant',
  'yakitori_restaurant',
]

export const GOOGLE_TYPE_TO_PLACE_CATEGORY = {
  korean_restaurant: 'korean',
  korean_barbecue_restaurant: 'korean',

  cantonese_restaurant: 'chinese',
  chinese_noodle_restaurant: 'chinese',
  chinese_restaurant: 'chinese',
  dim_sum_restaurant: 'chinese',
  dumpling_restaurant: 'chinese',
  hot_pot_restaurant: 'chinese',

  japanese_curry_restaurant: 'japanese',
  japanese_izakaya_restaurant: 'japanese',
  japanese_restaurant: 'japanese',
  ramen_restaurant: 'japanese',
  sushi_restaurant: 'japanese',
  tonkatsu_restaurant: 'japanese',
  yakiniku_restaurant: 'japanese',
  yakitori_restaurant: 'japanese',

  american_restaurant: 'western',
  australian_restaurant: 'western',
  austrian_restaurant: 'western',
  basque_restaurant: 'western',
  bavarian_restaurant: 'western',
  belgian_restaurant: 'western',
  bistro: 'western',
  british_restaurant: 'western',
  cajun_restaurant: 'western',
  californian_restaurant: 'western',
  croatian_restaurant: 'western',
  czech_restaurant: 'western',
  danish_restaurant: 'western',
  dutch_restaurant: 'western',
  eastern_european_restaurant: 'western',
  european_restaurant: 'western',
  fish_and_chips_restaurant: 'western',
  fondue_restaurant: 'western',
  french_restaurant: 'western',
  german_restaurant: 'western',
  greek_restaurant: 'western',
  hamburger_restaurant: 'western',
  hungarian_restaurant: 'western',
  irish_restaurant: 'western',
  italian_restaurant: 'western',
  mediterranean_restaurant: 'western',
  pizza_restaurant: 'western',
  polish_restaurant: 'western',
  portuguese_restaurant: 'western',
  romanian_restaurant: 'western',
  russian_restaurant: 'western',
  scandinavian_restaurant: 'western',
  southwestern_us_restaurant: 'western',
  spanish_restaurant: 'western',
  steak_house: 'western',
  swiss_restaurant: 'western',
  tapas_restaurant: 'western',
  ukrainian_restaurant: 'western',
  western_restaurant: 'western',

  asian_fusion_restaurant: 'asian',
  asian_restaurant: 'asian',
  bangladeshi_restaurant: 'asian',
  burmese_restaurant: 'asian',
  cambodian_restaurant: 'asian',
  filipino_restaurant: 'asian',
  indian_restaurant: 'asian',
  indonesian_restaurant: 'asian',
  malaysian_restaurant: 'asian',
  mongolian_barbecue_restaurant: 'asian',
  north_indian_restaurant: 'asian',
  pakistani_restaurant: 'asian',
  south_indian_restaurant: 'asian',
  sri_lankan_restaurant: 'asian',
  taiwanese_restaurant: 'asian',
  thai_restaurant: 'asian',
  tibetan_restaurant: 'asian',
  vietnamese_restaurant: 'asian',

  afghani_restaurant: 'global',
  african_restaurant: 'global',
  argentinian_restaurant: 'global',
  barbecue_restaurant: 'global',
  brazilian_restaurant: 'global',
  burrito_restaurant: 'global',
  caribbean_restaurant: 'global',
  chilean_restaurant: 'global',
  colombian_restaurant: 'global',
  cuban_restaurant: 'global',
  ethiopian_restaurant: 'global',
  falafel_restaurant: 'global',
  fusion_restaurant: 'global',
  gyro_restaurant: 'global',
  halal_restaurant: 'global',
  hawaiian_restaurant: 'global',
  israeli_restaurant: 'global',
  kebab_shop: 'global',
  latin_american_restaurant: 'global',
  lebanese_restaurant: 'global',
  mexican_restaurant: 'global',
  middle_eastern_restaurant: 'global',
  moroccan_restaurant: 'global',
  persian_restaurant: 'global',
  peruvian_restaurant: 'global',
  shawarma_restaurant: 'global',
  soul_food_restaurant: 'global',
  south_american_restaurant: 'global',
  taco_restaurant: 'global',
  tex_mex_restaurant: 'global',
  turkish_restaurant: 'global',

  bagel_shop: 'quick',
  breakfast_restaurant: 'quick',
  brunch_restaurant: 'quick',
  cafeteria: 'quick',
  chicken_restaurant: 'quick',
  chicken_wings_restaurant: 'quick',
  deli: 'quick',
  diner: 'quick',
  fast_food_restaurant: 'quick',
  food_court: 'quick',
  hot_dog_restaurant: 'quick',
  hot_dog_stand: 'quick',
  meal_delivery: 'quick',
  meal_takeaway: 'quick',
  noodle_shop: 'quick',
  pizza_delivery: 'quick',
  salad_shop: 'quick',
  sandwich_shop: 'quick',
  snack_bar: 'quick',
  soup_restaurant: 'quick',

  acai_shop: 'cafe',
  bakery: 'cafe',
  cafe: 'cafe',
  cake_shop: 'cafe',
  candy_store: 'cafe',
  cat_cafe: 'cafe',
  chocolate_factory: 'cafe',
  chocolate_shop: 'cafe',
  coffee_roastery: 'cafe',
  coffee_shop: 'cafe',
  coffee_stand: 'cafe',
  confectionery: 'cafe',
  dessert_restaurant: 'cafe',
  dessert_shop: 'cafe',
  dog_cafe: 'cafe',
  donut_shop: 'cafe',
  ice_cream_shop: 'cafe',
  juice_shop: 'cafe',
  pastry_shop: 'cafe',
  tea_house: 'cafe',

  bar: 'bar',
  bar_and_grill: 'bar',
  beer_garden: 'bar',
  brewery: 'bar',
  brewpub: 'bar',
  cocktail_bar: 'bar',
  gastropub: 'bar',
  hookah_bar: 'bar',
  irish_pub: 'bar',
  lounge_bar: 'bar',
  oyster_bar_restaurant: 'bar',
  pub: 'bar',
  sports_bar: 'bar',
  wine_bar: 'bar',
  winery: 'bar',

  buffet_restaurant: 'other',
  family_restaurant: 'other',
  fine_dining_restaurant: 'other',
  restaurant: 'other',
  seafood_restaurant: 'other',
  vegan_restaurant: 'other',
  vegetarian_restaurant: 'other',
}
